### ISSUE TITLE
Fatal error: spawn EMFILE 

### ISSUE THREAD

**Issue by praveenvijayan** [yoheiMune/grunt-compass-multiple#3]
Getting "Fatal error: spawn EMFILE " when tries to run server. I'm on node v0.10.7. 
![screen shot 2013-05-21 at 3 06 11 pm](https://f.cloud.github.com/assets/176655/540889/317d2194-c1fa-11e2-9227-6d94356f0f41.png)

**Comment by yoheiMune** [comment]
Thank you for your bug report.
Now, I am going to checking and fixing this bug.

Thank you.

**Comment by yoheiMune** [comment]
I found similar situation. Is the link below available for you?

https://github.com/gruntjs/grunt/issues/788
