### ISSUE TITLE
Running it with multiple tasks?

### ISSUE THREAD

**Issue by jnsandrew** [yoheiMune/grunt-compass-multiple#8]
Is there anyway to run this task with other tasks? I'm trying to use it with grunt watch,

sass: {
        options: {
          livereload: false,
        },
        files: ['app/styles/**/*.{scss,sass}', 'app/modules/**/*.{scss,sass}'],
        tasks: ['compassMultiple:app', 'autoprefixer:app']
      },

But autoprefixer doesn't run. Is there an option somewhere?

**Comment by yoheiMune** [comment]
Hi, jnsandrew!

I don't know autoprefixer much, but autoprefixer need "CSS" inputs, maybe?
In this case, the output directory of compassMultiple should be set at the input directory of autoprefixer.

With "cssDir" option, you can specify a css output directory of this task.
Please check at README for more detail.

Is this answer useful for you?

Thank you for trying grunt-compass-multiple.

Yohei Munesada

**Comment by jnsandrew** [comment]
Hey,

No, I couldn't get it to work with autoprefixer in the end - it looks like this task is a blocker, a bit like how grunt watch / grunt connect work, you run the task and no tasks get run after? I'm not sure but that's my theory.

In the end I decided I didn't need compass in the end and got what I wanted to work just using the regular sass task.
